title: Cloud4est Members
description: Members of Cloud4est
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://members.cloud4est.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  members:
    title: Members
    output: true
    permalink: "/members/:path"

defaults:
  - scope:
      path: ''
      type: members
    values:
      layout: member
