---
title: Cloud4est Members
timezone: UTC
collections:
  members:
    title: Members
    output: true
    permalink: "/members/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: members
  values:
    layout: member
description: Members of Cloud4est
baseurl: ''
url: members.cloud4est.com
markdown: kramdown
plugins:
- jekyll-feed
